on:
  push: 
    branches:
      - main

name: Update Application in Prod
jobs:
  build:
    name: Run Scripts on EC2
    runs-on: ubuntu-latest
    steps:      
      - name: Execute pull scripts on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /home/ec2-user/byte-server
            git pull
            go build -o app .
            sudo systemctl restart byteserver